name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install linting tools
        run: |
          pip install black isort pylint

      # -----------------------
      # Code Quality Checks
      # -----------------------

      - name: Run Black formatter check
        run: |
          black --check .

      - name: Run isort check
        run: |
          isort . --check-only

      - name: Run pylint
        run: |
          pylint src/bsort || true

      # -----------------------
      # Unit Tests
      # -----------------------

      - name: Run tests
        run: |
          pytest -q

      # -----------------------
      # Docker Build
      # -----------------------

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t bsort:latest .
  